// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetSchemasIdsIDVersionsParams creates a new GetSchemasIdsIDVersionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSchemasIdsIDVersionsParams() *GetSchemasIdsIDVersionsParams {
	return &GetSchemasIdsIDVersionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSchemasIdsIDVersionsParamsWithTimeout creates a new GetSchemasIdsIDVersionsParams object
// with the ability to set a timeout on a request.
func NewGetSchemasIdsIDVersionsParamsWithTimeout(timeout time.Duration) *GetSchemasIdsIDVersionsParams {
	return &GetSchemasIdsIDVersionsParams{
		timeout: timeout,
	}
}

// NewGetSchemasIdsIDVersionsParamsWithContext creates a new GetSchemasIdsIDVersionsParams object
// with the ability to set a context for a request.
func NewGetSchemasIdsIDVersionsParamsWithContext(ctx context.Context) *GetSchemasIdsIDVersionsParams {
	return &GetSchemasIdsIDVersionsParams{
		Context: ctx,
	}
}

// NewGetSchemasIdsIDVersionsParamsWithHTTPClient creates a new GetSchemasIdsIDVersionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSchemasIdsIDVersionsParamsWithHTTPClient(client *http.Client) *GetSchemasIdsIDVersionsParams {
	return &GetSchemasIdsIDVersionsParams{
		HTTPClient: client,
	}
}

/*
GetSchemasIdsIDVersionsParams contains all the parameters to send to the API endpoint

	for the get schemas ids id versions operation.

	Typically these are written to a http.Request.
*/
type GetSchemasIdsIDVersionsParams struct {

	// ID.
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get schemas ids id versions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSchemasIdsIDVersionsParams) WithDefaults() *GetSchemasIdsIDVersionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get schemas ids id versions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSchemasIdsIDVersionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get schemas ids id versions params
func (o *GetSchemasIdsIDVersionsParams) WithTimeout(timeout time.Duration) *GetSchemasIdsIDVersionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get schemas ids id versions params
func (o *GetSchemasIdsIDVersionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get schemas ids id versions params
func (o *GetSchemasIdsIDVersionsParams) WithContext(ctx context.Context) *GetSchemasIdsIDVersionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get schemas ids id versions params
func (o *GetSchemasIdsIDVersionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get schemas ids id versions params
func (o *GetSchemasIdsIDVersionsParams) WithHTTPClient(client *http.Client) *GetSchemasIdsIDVersionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get schemas ids id versions params
func (o *GetSchemasIdsIDVersionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get schemas ids id versions params
func (o *GetSchemasIdsIDVersionsParams) WithID(id int64) *GetSchemasIdsIDVersionsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get schemas ids id versions params
func (o *GetSchemasIdsIDVersionsParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetSchemasIdsIDVersionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
