// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetConfigSubjectParams creates a new GetConfigSubjectParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetConfigSubjectParams() *GetConfigSubjectParams {
	return &GetConfigSubjectParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetConfigSubjectParamsWithTimeout creates a new GetConfigSubjectParams object
// with the ability to set a timeout on a request.
func NewGetConfigSubjectParamsWithTimeout(timeout time.Duration) *GetConfigSubjectParams {
	return &GetConfigSubjectParams{
		timeout: timeout,
	}
}

// NewGetConfigSubjectParamsWithContext creates a new GetConfigSubjectParams object
// with the ability to set a context for a request.
func NewGetConfigSubjectParamsWithContext(ctx context.Context) *GetConfigSubjectParams {
	return &GetConfigSubjectParams{
		Context: ctx,
	}
}

// NewGetConfigSubjectParamsWithHTTPClient creates a new GetConfigSubjectParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetConfigSubjectParamsWithHTTPClient(client *http.Client) *GetConfigSubjectParams {
	return &GetConfigSubjectParams{
		HTTPClient: client,
	}
}

/*
GetConfigSubjectParams contains all the parameters to send to the API endpoint

	for the get config subject operation.

	Typically these are written to a http.Request.
*/
type GetConfigSubjectParams struct {

	// Subject.
	Subject string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get config subject params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetConfigSubjectParams) WithDefaults() *GetConfigSubjectParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get config subject params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetConfigSubjectParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get config subject params
func (o *GetConfigSubjectParams) WithTimeout(timeout time.Duration) *GetConfigSubjectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get config subject params
func (o *GetConfigSubjectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get config subject params
func (o *GetConfigSubjectParams) WithContext(ctx context.Context) *GetConfigSubjectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get config subject params
func (o *GetConfigSubjectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get config subject params
func (o *GetConfigSubjectParams) WithHTTPClient(client *http.Client) *GetConfigSubjectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get config subject params
func (o *GetConfigSubjectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSubject adds the subject to the get config subject params
func (o *GetConfigSubjectParams) WithSubject(subject string) *GetConfigSubjectParams {
	o.SetSubject(subject)
	return o
}

// SetSubject adds the subject to the get config subject params
func (o *GetConfigSubjectParams) SetSubject(subject string) {
	o.Subject = subject
}

// WriteToRequest writes these params to a swagger request
func (o *GetConfigSubjectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param subject
	if err := r.SetPathParam("subject", o.Subject); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
