// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSubjectVersionsParams creates a new GetSubjectVersionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSubjectVersionsParams() *GetSubjectVersionsParams {
	return &GetSubjectVersionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSubjectVersionsParamsWithTimeout creates a new GetSubjectVersionsParams object
// with the ability to set a timeout on a request.
func NewGetSubjectVersionsParamsWithTimeout(timeout time.Duration) *GetSubjectVersionsParams {
	return &GetSubjectVersionsParams{
		timeout: timeout,
	}
}

// NewGetSubjectVersionsParamsWithContext creates a new GetSubjectVersionsParams object
// with the ability to set a context for a request.
func NewGetSubjectVersionsParamsWithContext(ctx context.Context) *GetSubjectVersionsParams {
	return &GetSubjectVersionsParams{
		Context: ctx,
	}
}

// NewGetSubjectVersionsParamsWithHTTPClient creates a new GetSubjectVersionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSubjectVersionsParamsWithHTTPClient(client *http.Client) *GetSubjectVersionsParams {
	return &GetSubjectVersionsParams{
		HTTPClient: client,
	}
}

/*
GetSubjectVersionsParams contains all the parameters to send to the API endpoint

	for the get subject versions operation.

	Typically these are written to a http.Request.
*/
type GetSubjectVersionsParams struct {

	// Deleted.
	Deleted *string

	// Subject.
	Subject string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get subject versions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSubjectVersionsParams) WithDefaults() *GetSubjectVersionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get subject versions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSubjectVersionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get subject versions params
func (o *GetSubjectVersionsParams) WithTimeout(timeout time.Duration) *GetSubjectVersionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get subject versions params
func (o *GetSubjectVersionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get subject versions params
func (o *GetSubjectVersionsParams) WithContext(ctx context.Context) *GetSubjectVersionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get subject versions params
func (o *GetSubjectVersionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get subject versions params
func (o *GetSubjectVersionsParams) WithHTTPClient(client *http.Client) *GetSubjectVersionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get subject versions params
func (o *GetSubjectVersionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeleted adds the deleted to the get subject versions params
func (o *GetSubjectVersionsParams) WithDeleted(deleted *string) *GetSubjectVersionsParams {
	o.SetDeleted(deleted)
	return o
}

// SetDeleted adds the deleted to the get subject versions params
func (o *GetSubjectVersionsParams) SetDeleted(deleted *string) {
	o.Deleted = deleted
}

// WithSubject adds the subject to the get subject versions params
func (o *GetSubjectVersionsParams) WithSubject(subject string) *GetSubjectVersionsParams {
	o.SetSubject(subject)
	return o
}

// SetSubject adds the subject to the get subject versions params
func (o *GetSubjectVersionsParams) SetSubject(subject string) {
	o.Subject = subject
}

// WriteToRequest writes these params to a swagger request
func (o *GetSubjectVersionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Deleted != nil {

		// query param deleted
		var qrDeleted string

		if o.Deleted != nil {
			qrDeleted = *o.Deleted
		}
		qDeleted := qrDeleted
		if qDeleted != "" {

			if err := r.SetQueryParam("deleted", qDeleted); err != nil {
				return err
			}
		}
	}

	// path param subject
	if err := r.SetPathParam("subject", o.Subject); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
