// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"redpanda-schema-registry/models"
)

// GetSchemasTypesReader is a Reader for the GetSchemasTypes structure.
type GetSchemasTypesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSchemasTypesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetSchemasTypesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetSchemasTypesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /schemas/types] get_schemas_types", response, response.Code())
	}
}

// NewGetSchemasTypesOK creates a GetSchemasTypesOK with default headers values
func NewGetSchemasTypesOK() *GetSchemasTypesOK {
	return &GetSchemasTypesOK{}
}

/*
GetSchemasTypesOK describes a response with status code 200, with default header values.

OK
*/
type GetSchemasTypesOK struct {
	Payload []string
}

// IsSuccess returns true when this get schemas types o k response has a 2xx status code
func (o *GetSchemasTypesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get schemas types o k response has a 3xx status code
func (o *GetSchemasTypesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get schemas types o k response has a 4xx status code
func (o *GetSchemasTypesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get schemas types o k response has a 5xx status code
func (o *GetSchemasTypesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get schemas types o k response a status code equal to that given
func (o *GetSchemasTypesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get schemas types o k response
func (o *GetSchemasTypesOK) Code() int {
	return 200
}

func (o *GetSchemasTypesOK) Error() string {
	return fmt.Sprintf("[GET /schemas/types][%d] getSchemasTypesOK  %+v", 200, o.Payload)
}

func (o *GetSchemasTypesOK) String() string {
	return fmt.Sprintf("[GET /schemas/types][%d] getSchemasTypesOK  %+v", 200, o.Payload)
}

func (o *GetSchemasTypesOK) GetPayload() []string {
	return o.Payload
}

func (o *GetSchemasTypesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSchemasTypesInternalServerError creates a GetSchemasTypesInternalServerError with default headers values
func NewGetSchemasTypesInternalServerError() *GetSchemasTypesInternalServerError {
	return &GetSchemasTypesInternalServerError{}
}

/*
GetSchemasTypesInternalServerError describes a response with status code 500, with default header values.

Internal Server error
*/
type GetSchemasTypesInternalServerError struct {
	Payload *models.ErrorBody
}

// IsSuccess returns true when this get schemas types internal server error response has a 2xx status code
func (o *GetSchemasTypesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get schemas types internal server error response has a 3xx status code
func (o *GetSchemasTypesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get schemas types internal server error response has a 4xx status code
func (o *GetSchemasTypesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get schemas types internal server error response has a 5xx status code
func (o *GetSchemasTypesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get schemas types internal server error response a status code equal to that given
func (o *GetSchemasTypesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get schemas types internal server error response
func (o *GetSchemasTypesInternalServerError) Code() int {
	return 500
}

func (o *GetSchemasTypesInternalServerError) Error() string {
	return fmt.Sprintf("[GET /schemas/types][%d] getSchemasTypesInternalServerError  %+v", 500, o.Payload)
}

func (o *GetSchemasTypesInternalServerError) String() string {
	return fmt.Sprintf("[GET /schemas/types][%d] getSchemasTypesInternalServerError  %+v", 500, o.Payload)
}

func (o *GetSchemasTypesInternalServerError) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetSchemasTypesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
