// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"redpanda-schema-registry/models"
)

// GetConfigSubjectReader is a Reader for the GetConfigSubject structure.
type GetConfigSubjectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetConfigSubjectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetConfigSubjectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetConfigSubjectInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /config/{subject}] get_config_subject", response, response.Code())
	}
}

// NewGetConfigSubjectOK creates a GetConfigSubjectOK with default headers values
func NewGetConfigSubjectOK() *GetConfigSubjectOK {
	return &GetConfigSubjectOK{}
}

/*
GetConfigSubjectOK describes a response with status code 200, with default header values.

OK
*/
type GetConfigSubjectOK struct {
	Payload *GetConfigSubjectOKBody
}

// IsSuccess returns true when this get config subject o k response has a 2xx status code
func (o *GetConfigSubjectOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get config subject o k response has a 3xx status code
func (o *GetConfigSubjectOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get config subject o k response has a 4xx status code
func (o *GetConfigSubjectOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get config subject o k response has a 5xx status code
func (o *GetConfigSubjectOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get config subject o k response a status code equal to that given
func (o *GetConfigSubjectOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get config subject o k response
func (o *GetConfigSubjectOK) Code() int {
	return 200
}

func (o *GetConfigSubjectOK) Error() string {
	return fmt.Sprintf("[GET /config/{subject}][%d] getConfigSubjectOK  %+v", 200, o.Payload)
}

func (o *GetConfigSubjectOK) String() string {
	return fmt.Sprintf("[GET /config/{subject}][%d] getConfigSubjectOK  %+v", 200, o.Payload)
}

func (o *GetConfigSubjectOK) GetPayload() *GetConfigSubjectOKBody {
	return o.Payload
}

func (o *GetConfigSubjectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(GetConfigSubjectOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetConfigSubjectInternalServerError creates a GetConfigSubjectInternalServerError with default headers values
func NewGetConfigSubjectInternalServerError() *GetConfigSubjectInternalServerError {
	return &GetConfigSubjectInternalServerError{}
}

/*
GetConfigSubjectInternalServerError describes a response with status code 500, with default header values.

Internal Server error
*/
type GetConfigSubjectInternalServerError struct {
	Payload *models.ErrorBody
}

// IsSuccess returns true when this get config subject internal server error response has a 2xx status code
func (o *GetConfigSubjectInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get config subject internal server error response has a 3xx status code
func (o *GetConfigSubjectInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get config subject internal server error response has a 4xx status code
func (o *GetConfigSubjectInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get config subject internal server error response has a 5xx status code
func (o *GetConfigSubjectInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get config subject internal server error response a status code equal to that given
func (o *GetConfigSubjectInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get config subject internal server error response
func (o *GetConfigSubjectInternalServerError) Code() int {
	return 500
}

func (o *GetConfigSubjectInternalServerError) Error() string {
	return fmt.Sprintf("[GET /config/{subject}][%d] getConfigSubjectInternalServerError  %+v", 500, o.Payload)
}

func (o *GetConfigSubjectInternalServerError) String() string {
	return fmt.Sprintf("[GET /config/{subject}][%d] getConfigSubjectInternalServerError  %+v", 500, o.Payload)
}

func (o *GetConfigSubjectInternalServerError) GetPayload() *models.ErrorBody {
	return o.Payload
}

func (o *GetConfigSubjectInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
GetConfigSubjectOKBody get config subject o k body
swagger:model GetConfigSubjectOKBody
*/
type GetConfigSubjectOKBody struct {

	// compatibility level
	CompatibilityLevel string `json:"compatibilityLevel,omitempty"`
}

// Validate validates this get config subject o k body
func (o *GetConfigSubjectOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get config subject o k body based on context it is used
func (o *GetConfigSubjectOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetConfigSubjectOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetConfigSubjectOKBody) UnmarshalBinary(b []byte) error {
	var res GetConfigSubjectOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
