// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSubjectVersionsVersionReferencedByParams creates a new GetSubjectVersionsVersionReferencedByParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetSubjectVersionsVersionReferencedByParams() *GetSubjectVersionsVersionReferencedByParams {
	return &GetSubjectVersionsVersionReferencedByParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetSubjectVersionsVersionReferencedByParamsWithTimeout creates a new GetSubjectVersionsVersionReferencedByParams object
// with the ability to set a timeout on a request.
func NewGetSubjectVersionsVersionReferencedByParamsWithTimeout(timeout time.Duration) *GetSubjectVersionsVersionReferencedByParams {
	return &GetSubjectVersionsVersionReferencedByParams{
		timeout: timeout,
	}
}

// NewGetSubjectVersionsVersionReferencedByParamsWithContext creates a new GetSubjectVersionsVersionReferencedByParams object
// with the ability to set a context for a request.
func NewGetSubjectVersionsVersionReferencedByParamsWithContext(ctx context.Context) *GetSubjectVersionsVersionReferencedByParams {
	return &GetSubjectVersionsVersionReferencedByParams{
		Context: ctx,
	}
}

// NewGetSubjectVersionsVersionReferencedByParamsWithHTTPClient creates a new GetSubjectVersionsVersionReferencedByParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetSubjectVersionsVersionReferencedByParamsWithHTTPClient(client *http.Client) *GetSubjectVersionsVersionReferencedByParams {
	return &GetSubjectVersionsVersionReferencedByParams{
		HTTPClient: client,
	}
}

/*
GetSubjectVersionsVersionReferencedByParams contains all the parameters to send to the API endpoint

	for the get subject versions version referenced by operation.

	Typically these are written to a http.Request.
*/
type GetSubjectVersionsVersionReferencedByParams struct {

	// Subject.
	Subject string

	// Version.
	Version string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get subject versions version referenced by params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSubjectVersionsVersionReferencedByParams) WithDefaults() *GetSubjectVersionsVersionReferencedByParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get subject versions version referenced by params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetSubjectVersionsVersionReferencedByParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get subject versions version referenced by params
func (o *GetSubjectVersionsVersionReferencedByParams) WithTimeout(timeout time.Duration) *GetSubjectVersionsVersionReferencedByParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get subject versions version referenced by params
func (o *GetSubjectVersionsVersionReferencedByParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get subject versions version referenced by params
func (o *GetSubjectVersionsVersionReferencedByParams) WithContext(ctx context.Context) *GetSubjectVersionsVersionReferencedByParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get subject versions version referenced by params
func (o *GetSubjectVersionsVersionReferencedByParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get subject versions version referenced by params
func (o *GetSubjectVersionsVersionReferencedByParams) WithHTTPClient(client *http.Client) *GetSubjectVersionsVersionReferencedByParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get subject versions version referenced by params
func (o *GetSubjectVersionsVersionReferencedByParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSubject adds the subject to the get subject versions version referenced by params
func (o *GetSubjectVersionsVersionReferencedByParams) WithSubject(subject string) *GetSubjectVersionsVersionReferencedByParams {
	o.SetSubject(subject)
	return o
}

// SetSubject adds the subject to the get subject versions version referenced by params
func (o *GetSubjectVersionsVersionReferencedByParams) SetSubject(subject string) {
	o.Subject = subject
}

// WithVersion adds the version to the get subject versions version referenced by params
func (o *GetSubjectVersionsVersionReferencedByParams) WithVersion(version string) *GetSubjectVersionsVersionReferencedByParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the get subject versions version referenced by params
func (o *GetSubjectVersionsVersionReferencedByParams) SetVersion(version string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *GetSubjectVersionsVersionReferencedByParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param subject
	if err := r.SetPathParam("subject", o.Subject); err != nil {
		return err
	}

	// path param version
	if err := r.SetPathParam("version", o.Version); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
