// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"redpanda-schema-registry/models"
)

// NewPostSubjectParams creates a new PostSubjectParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostSubjectParams() *PostSubjectParams {
	return &PostSubjectParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostSubjectParamsWithTimeout creates a new PostSubjectParams object
// with the ability to set a timeout on a request.
func NewPostSubjectParamsWithTimeout(timeout time.Duration) *PostSubjectParams {
	return &PostSubjectParams{
		timeout: timeout,
	}
}

// NewPostSubjectParamsWithContext creates a new PostSubjectParams object
// with the ability to set a context for a request.
func NewPostSubjectParamsWithContext(ctx context.Context) *PostSubjectParams {
	return &PostSubjectParams{
		Context: ctx,
	}
}

// NewPostSubjectParamsWithHTTPClient creates a new PostSubjectParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostSubjectParamsWithHTTPClient(client *http.Client) *PostSubjectParams {
	return &PostSubjectParams{
		HTTPClient: client,
	}
}

/*
PostSubjectParams contains all the parameters to send to the API endpoint

	for the post subject operation.

	Typically these are written to a http.Request.
*/
type PostSubjectParams struct {

	// SchemaDef.
	SchemaDef *models.SchemaDef

	// Subject.
	Subject string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post subject params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostSubjectParams) WithDefaults() *PostSubjectParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post subject params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostSubjectParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post subject params
func (o *PostSubjectParams) WithTimeout(timeout time.Duration) *PostSubjectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post subject params
func (o *PostSubjectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post subject params
func (o *PostSubjectParams) WithContext(ctx context.Context) *PostSubjectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post subject params
func (o *PostSubjectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post subject params
func (o *PostSubjectParams) WithHTTPClient(client *http.Client) *PostSubjectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post subject params
func (o *PostSubjectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSchemaDef adds the schemaDef to the post subject params
func (o *PostSubjectParams) WithSchemaDef(schemaDef *models.SchemaDef) *PostSubjectParams {
	o.SetSchemaDef(schemaDef)
	return o
}

// SetSchemaDef adds the schemaDef to the post subject params
func (o *PostSubjectParams) SetSchemaDef(schemaDef *models.SchemaDef) {
	o.SchemaDef = schemaDef
}

// WithSubject adds the subject to the post subject params
func (o *PostSubjectParams) WithSubject(subject string) *PostSubjectParams {
	o.SetSubject(subject)
	return o
}

// SetSubject adds the subject to the post subject params
func (o *PostSubjectParams) SetSubject(subject string) {
	o.Subject = subject
}

// WriteToRequest writes these params to a swagger request
func (o *PostSubjectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.SchemaDef != nil {
		if err := r.SetBodyParam(o.SchemaDef); err != nil {
			return err
		}
	}

	// path param subject
	if err := r.SetPathParam("subject", o.Subject); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
