// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SubjectSchema subject schema
//
// swagger:model subject_schema
type SubjectSchema struct {

	// id
	ID int64 `json:"id,omitempty"`

	// references
	References []*SubjectSchemaReferencesItems0 `json:"references"`

	// schema
	Schema string `json:"schema,omitempty"`

	// schema type
	SchemaType string `json:"schemaType,omitempty"`

	// subject
	Subject string `json:"subject,omitempty"`

	// version
	Version int64 `json:"version,omitempty"`
}

// Validate validates this subject schema
func (m *SubjectSchema) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReferences(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SubjectSchema) validateReferences(formats strfmt.Registry) error {
	if swag.IsZero(m.References) { // not required
		return nil
	}

	for i := 0; i < len(m.References); i++ {
		if swag.IsZero(m.References[i]) { // not required
			continue
		}

		if m.References[i] != nil {
			if err := m.References[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("references" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("references" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this subject schema based on the context it is used
func (m *SubjectSchema) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateReferences(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SubjectSchema) contextValidateReferences(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.References); i++ {

		if m.References[i] != nil {

			if swag.IsZero(m.References[i]) { // not required
				return nil
			}

			if err := m.References[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("references" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("references" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SubjectSchema) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SubjectSchema) UnmarshalBinary(b []byte) error {
	var res SubjectSchema
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// SubjectSchemaReferencesItems0 subject schema references items0
//
// swagger:model SubjectSchemaReferencesItems0
type SubjectSchemaReferencesItems0 struct {

	// name
	Name string `json:"name,omitempty"`

	// subject
	Subject string `json:"subject,omitempty"`

	// version
	Version int64 `json:"version,omitempty"`
}

// Validate validates this subject schema references items0
func (m *SubjectSchemaReferencesItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this subject schema references items0 based on context it is used
func (m *SubjectSchemaReferencesItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SubjectSchemaReferencesItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SubjectSchemaReferencesItems0) UnmarshalBinary(b []byte) error {
	var res SubjectSchemaReferencesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
